version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: festywise_admin
      POSTGRES_PASSWORD: bakuBot2022
  backend:
    build: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
  fontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/frontend-app
      - ./frontend/node_modules:/frontend-app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - db
      - backend
